### ISSUE TITLE
Navbar Creation

### ISSUE THREAD

**Issue by amillion3** [nss-evening-cohort-7/bandz-semi-solids#2]
# Story
As a user, in order to navigate our awesomely fantastic website, I need to create a navbar to navigate to all the pages or our site.

# Acceptance Criteria
**When** the user arrives on the site there should be a navbar underneath the logo and band photo heading
**Then** the navbar should take the user to different pages on the site via link
**And** the navbar should be clickable
**And** it should span the width of the page
**And** it should highlight on hover

# Technical Notes
this needs to be placed on every page before styling on other pages
styling: font color should be gold, on hover turn red

**Comment by amillion3** [comment]
<img width="573" alt="screen shot 2018-03-12 at 8 50 04 pm" src="https://user-images.githubusercontent.com/20422019/37318174-0899211e-2637-11e8-808e-8dd4d1589402.png">

**Comment by maryaliceorr** [comment]
# Story

As a user, in order to navigate our awesomely fantastic website, I need to create a navbar to navigate to all the pages or our site.

# Acceptance Criteria

**When**: the user arrives on the site there should be a navbar underneath the logo and band photo heading
**Then**: the navbar should take the user to different pages on the site via link
**And**: the navbar should be clickable
**And**: it should span the width of the page
**And**: it should highlight on hover

# Technical Notes

- this needs to be placed on every page before styling on other pages
- styling: font color should be gold, on hover turn red
